/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/jobs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retrieve all jobs */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example success */
              info: string;
              data: components['schemas']['Job'][];
            };
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateJob'];
        };
      };
      responses: {
        /** @description Create a new job */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Success'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UnauthorizedError'];
          };
        };
        /** @description Validation error */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidationError'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/jobs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retrieve a job by ID */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @example success */
              info: string;
              data: components['schemas']['Job'];
            };
          };
        };
        /** @description Job not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Job: {
      /** Format: date */
      createdAt: string | null;
      /** Format: date */
      updatedAt: string | null;
      /** Format: date */
      deletedAt: string | null;
      id: string;
      createdBy: string;
      company: string;
      position: string;
      location: string;
      /** @enum {string} */
      stage: 'Saved' | 'Applied' | 'Interview' | 'Offer';
      /** @enum {string|null} */
      type: 'On-site' | 'Hybrid' | 'Remote' | null;
      salary: number | null;
      companyUrl: string | null;
      applicationUrl: string | null;
      interviewDate: string | null;
      interviewType: string | null;
    };
    Error: {
      /** @example error */
      info: string;
      /** @example Job not found */
      error: string;
    };
    Success: {
      /** @example success */
      info: string;
      /** @description Response data */
      data?: unknown;
    };
    UnauthorizedError: {
      /** @example error */
      info: string;
      /** @example Unauthorized */
      error: string;
    };
    ValidationError: {
      /** @example validation error */
      info: string;
      /** @description Validation errors */
      errors: {
        /** @example invalid_type */
        code: string;
        /** @example Required */
        message: string;
        /**
         * @example [
         *       "company"
         *     ]
         */
        path: string;
      }[];
    };
    CreateJob: {
      createdBy: string;
      company: string;
      position: string;
      location: string;
      /** @enum {string} */
      stage: 'Saved' | 'Applied' | 'Interview' | 'Offer';
      /** @enum {string|null} */
      type?: 'On-site' | 'Hybrid' | 'Remote' | null;
      salary?: number | null;
      companyUrl?: string | null;
      applicationUrl?: string | null;
      interviewDate?: string | null;
      interviewType?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
