/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardJobsRouteRouteImport } from './routes/dashboard/jobs/route'
import { Route as DashboardJobsChar123idChar125_modalRouteImport } from './routes/dashboard/jobs/{$id}_modal'
import { Route as DashboardJobsIdRouteImport } from './routes/dashboard/jobs/$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRouteRoute = DashboardJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsChar123idChar125_modalRoute =
  DashboardJobsChar123idChar125_modalRouteImport.update({
    id: '/{$id}_modal',
    path: '/{$id}_modal',
    getParentRoute: () => DashboardJobsRouteRoute,
  } as any)
const DashboardJobsIdRoute = DashboardJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/jobs/{$id}_modal': typeof DashboardJobsChar123idChar125_modalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/jobs/{$id}_modal': typeof DashboardJobsChar123idChar125_modalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/jobs/{$id}_modal': typeof DashboardJobsChar123idChar125_modalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/jobs'
    | '/dashboard/'
    | '/dashboard/jobs/$id'
    | '/dashboard/jobs/{$id}_modal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/jobs'
    | '/dashboard'
    | '/dashboard/jobs/$id'
    | '/dashboard/jobs/{$id}_modal'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/jobs'
    | '/dashboard/'
    | '/dashboard/jobs/$id'
    | '/dashboard/jobs/{$id}_modal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/{$id}_modal': {
      id: '/dashboard/jobs/{$id}_modal'
      path: '/{$id}_modal'
      fullPath: '/dashboard/jobs/{$id}_modal'
      preLoaderRoute: typeof DashboardJobsChar123idChar125_modalRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/jobs/$id': {
      id: '/dashboard/jobs/$id'
      path: '/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
  }
}

interface DashboardJobsRouteRouteChildren {
  DashboardJobsIdRoute: typeof DashboardJobsIdRoute
  DashboardJobsChar123idChar125_modalRoute: typeof DashboardJobsChar123idChar125_modalRoute
}

const DashboardJobsRouteRouteChildren: DashboardJobsRouteRouteChildren = {
  DashboardJobsIdRoute: DashboardJobsIdRoute,
  DashboardJobsChar123idChar125_modalRoute:
    DashboardJobsChar123idChar125_modalRoute,
}

const DashboardJobsRouteRouteWithChildren =
  DashboardJobsRouteRoute._addFileChildren(DashboardJobsRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardJobsRouteRoute: typeof DashboardJobsRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardJobsRouteRoute: DashboardJobsRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
